@baseUrl = http://localhost:3001/api
@userId = 6a29e4ca39bc98a2984c01c3

### POST register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "auth-sys@example.com",
  "password": "Password123!"
}

### POST login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "auth-sys@example.com",
  "password": "Password123!"
}

### POST refresh access token
POST {{baseUrl}}/auth/refresh


### POST logout
POST {{baseUrl}}/auth/logout
