@baseUrl = http://localhost:3001/api
@userId = 6a3450cbb6ac0ba62ec6e3bd
@appId = 6a3458f09d70213273ae0ab8
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3ODIwNjY2MzIsImV4cCI6MTc4MjE1MzAzMiwic3ViIjoiNmEzNDUwY2JiNmFjMGJhNjJlYzZlM2JkIn0.uT7Ncrtn9k3Ji3uiLnojCRmlBumG0KOl1u32wDaL1Ws
@companyId = 6a345158b6ac0ba62ec6e3c1
@contactId = 6a3456d29d70213273ae0aa5
@applicationId = 6a3458f09d70213273ae0ab8
@taskId = 6a382e1d724b4c576c8a49f9



### User login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "app-test@example.com",
  "password": "Password123!"
}



### Create Application
POST {{baseUrl}}/apps
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Backend Developer Alpha",
  "description": "Application test with company and contact",
  "salaryMin": 45000,
  "salaryMax": 60000,
  "link": "https://example.com/jobs/backend-developer",
  "isFavorite": true,
  "status": "WATCHLIST",
  "company": "{{companyId}}",
  "contact": "{{contactId}}",
  "workLocation": "Essen",
  "workMode": "HYBRID",
  "appliedAt": "2026-06-18",
  "deadline": "2026-07-01",
  "followUpAt": "2026-06-25",
  "notes": "Created during Application CRUD test"
}

### Invalid Status
POST {{baseUrl}}/apps
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Java Developer",
  "status": "INVALID"
}

### Invalid companyId
POST {{baseUrl}}/apps
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "SAP Developer",
  "status": "WATCHLIST",
  "company": "666666666666666666666666"
}

### Invalid contactId
POST {{baseUrl}}/apps
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "SAP Developer",
  "status": "WATCHLIST",
  "contact": "666666666666666666666666"
}

### Get Apps
GET {{baseUrl}}/apps
Authorization: Bearer {{accessToken}}

### Get Application By Id
GET {{baseUrl}}/apps/{{appId}}
Authorization: Bearer {{accessToken}}

### Invalid appId
GET {{baseUrl}}/apps/666666666666666666666666
Authorization: Bearer {{accessToken}}

GET {{baseUrl}}/apps/abc
Authorization: Bearer {{accessToken}}

### Update Application
### Update status
PATCH {{baseUrl}}/apps/{{appId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "status": "INTERVIEW"
}

### Update isFavorite
PATCH {{baseUrl}}/apps/{{appId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "isFavorite": true
}

### Update companyId (invalid)
PATCH {{baseUrl}}/apps/{{appId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "company": "666666666666666666666666"
}

### Update contactId (invalid)
PATCH {{baseUrl}}/apps/{{appId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "contact": "666666666666666666666666"
}

# application
PATCH {{baseUrl}}/apps/666666666666666666666666
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "status": "INTERVIEW"
}

### Delete Application
DELETE {{baseUrl}}/apps/{{appId}}
Authorization: Bearer {{accessToken}}



### Create | Duplicate Task
POST {{baseUrl}}/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Prepare interview",
  "description": "Review company information",
  "status": "TODO",
  "application": "{{applicationId}}",
  "priority": 3
}

### Get Tasks
GET {{baseUrl}}/tasks
Authorization: Bearer {{accessToken}}

### Get Task By Id
GET {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{accessToken}}

### Update Status
PATCH {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}

### Update Priority
PATCH {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "priority": 5
}

### Update Multiple Fields
PATCH {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Prepare technical interview",
  "status": "DONE",
  "priority": 1
}

### Invalid Application
POST {{baseUrl}}/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Invalid Task",
  "status": "TODO",
  "application": "685555555555555555555555"
}

### Delete Task
DELETE {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{accessToken}}

### Get Deleted Task
GET {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{accessToken}}
