@baseUrl = http://localhost:3001/api
@userId = 6a2f3a7716b248a769867d39
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3ODE1NjM2NTUsImV4cCI6MTc4MTY1MDA1NSwic3ViIjoiNmEyOWU0Y2EzOWJjOThhMjk4NGMwMWMzIn0.fXOK_X2TqGu2tJO0xk5hrNPoCdtU3iz64ZsGpnrNb80



### POST register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "auth-sys@example.delete",
  "password": "Password123!"
}

### POST login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "auth-sys@example.com",
  "password": "Password123!"
}

### POST refresh access token
POST {{baseUrl}}/auth/refresh


### POST logout
POST {{baseUrl}}/auth/logout



### GET current user
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

### DELETE current user
DELETE {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}
